### ISSUE TITLE
Green in Virtual Enviroment runs python 2.7 instead of 3.* on OS X.

### ISSUE THREAD

**Issue by egrendah** [congredi/congredi#22]
Installed virtualenv and ran it. Green test passed when should have failed on python 3.* because green was using 2.7 even though the virtualenv was using python 3.*.

**Comment by Thetoxicarcade** [comment]
will need green to use the correct python version for OSX tests as well (#22)

**Comment by Thetoxicarcade** [comment]
@egrendah what are the outputs of:
```
python --version
green --version
virtualenv --version
source ~/2to3/bin/activate
python --version
green --version
```
need it to report the bug upstream.
